import { test, expect } from '@playwright/test';

test('responsive map commands and theme-only preferences preserve editing and saved styles', async ({ page }) => {
  test.setTimeout(240_000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const preferences = { version: 2, appearance: { theme: 'light' }, labels: { country: { font: 'serif', color: '#123456' }, place: { font: 'gothic', color: '#654321', pointColor: '#abcdef' } }, selection: { color: '#ff0000', outlineVisible: false, fillStrength: 0.8 } };
  await page.addInitScript(value => localStorage.setItem('pandolab-user-preferences', JSON.stringify(value)), preferences);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/?debug=1');
  await expect(page.locator('#app')).toHaveAttribute('data-readiness', 'enhanced', { timeout: 90_000 });
  await expect(page.locator('#mapToolToolbar,#engineStatus,#shortcutHelpModal,#keyboardHelpBtn,#objectCoastReconcileMenuBtn')).toHaveCount(0);
  await expect(page.locator('.map-command-toolbar')).toHaveCount(1);
  await expect(page.locator('#zoomInBtn,#zoomOutBtn,.map-view-toolbar')).toHaveCount(0);
  await expect(page.locator('#resetViewBtn')).toBeVisible();
  await expect(page.locator('[data-layer-group="genericFeatures"].layer-folder')).toBeHidden();
  await page.locator('#preferencesBtn').click();
  await expect(page.locator('#preferencesModal')).toBeVisible();
  await expect(page.locator('#preferencesModal input[type="color"]')).toHaveCount(0);
  await expect(page.locator('[data-preference-theme]')).toHaveCount(3);
  await expect(page.locator('[data-preference-accent]')).toHaveCount(7);
  await expect(page.locator('[data-preference-theme="light"]')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('#preferencesModal input[type="range"]')).toHaveCount(0);
  await page.locator('[data-preference-theme="dark"]').click();
  await expect(page.locator('[data-preference-theme="dark"]')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('[data-preference-theme="light"]')).toHaveAttribute('aria-pressed', 'false');
  await page.locator('#preferencesResetBtn').click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')).appearance.theme)).toBe('light');
  await page.locator('#preferencesCancelBtn').click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')))).toEqual(preferences);
  const interaction = await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection);
  expect(interaction.outlineVisible).toBe(preferences.selection.outlineVisible);
  expect(interaction.fillStrength).toBe(preferences.selection.fillStrength);
  expect(interaction.color).toBe(preferences.selection.color);
  await page.evaluate(() => window.PANDOLAB_TERRITORIAL.select('DEU'));
  await expect(page.locator('#entityProperties')).toBeVisible();
  await expect(page.locator('#editEntityBorderBtn')).toHaveCount(1);
  await page.locator('#preferencesBtn').click();
  const rulesBefore = await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle);
  await page.locator('[data-preference-accent="purple"]').click();
  await expect.poll(() => page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--accent').trim())).toBe('#7856d6');
  expect(await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection)).toEqual(interaction);
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')).appearance.accentPreset)).toBeUndefined();
  const rulesAfter = await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle);
  expect(rulesAfter.selection.primary).toEqual(rulesBefore.selection.primary);
  expect(rulesAfter.selection.secondary).toEqual(rulesBefore.selection.secondary);
  expect(rulesAfter.drawOrder).toEqual(rulesBefore.drawOrder);
  await page.locator('#preferencesApplyBtn').click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('pandolab-user-preferences')).appearance.accentPreset)).toBe('purple');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#app')).toHaveAttribute('data-layout', 'mobile');
  await expect(page.locator('#mobileEditBtn')).toHaveAttribute('aria-expanded', 'true');
  await page.locator('#mobileEditBtn').click();
  await expect(page.locator('#mobileEditBtn')).toHaveAttribute('aria-expanded', 'false');
  await expect(page.locator('#editorSurface')).toBeHidden();
  await expect(page.locator('.map-command-toolbar')).toHaveCount(1);
  await expect(page.locator('#zoomInBtn,#zoomOutBtn,.map-view-toolbar')).toHaveCount(0);
  await expect(page.locator('#resetViewBtn')).toBeVisible();
  const control = await page.locator('#resetViewBtn').boundingBox();
  expect(control.x).toBeGreaterThanOrEqual(0); expect(control.x + control.width).toBeLessThanOrEqual(391);
  const before = await page.evaluate(() => window.__PANDOLAB_VIEW_DEBUG__.snapshot().globeZoom);
  const map = await page.locator('#map').boundingBox();
  await page.mouse.move(map.x + map.width / 2, map.y + map.height / 2);
  await page.mouse.wheel(0, -500);
  await expect.poll(() => page.evaluate(() => window.__PANDOLAB_VIEW_DEBUG__.snapshot().globeZoom)).toBeGreaterThan(before);
  await page.locator('#resetViewBtn').click();
  await page.locator('#mobileMenuBtn').click();
  await page.locator('#mobilePreferencesBtn').click();
  await page.locator('[data-preference-accent="orange"]').click();
  await expect.poll(() => page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--accent').trim())).toBe('#dc781d');
  expect(await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection)).toEqual(interaction);
  await page.locator('#preferencesCancelBtn').click();
  await expect.poll(() => page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--accent').trim())).toBe('#7856d6');
  expect(await page.evaluate(() => window.__PANDOLAB_RENDER_DEBUG__.snapshot().interactionStyle.selection)).toEqual(interaction);
  expect(errors).toEqual([]);
});
