#!/usr/bin/env python3
"""Current-three fact mutations only; no omitted source, full-geometry or decoder replay."""
import copy,importlib.util,json,sys
from pathlib import Path
sys.dont_write_bytecode=True
HERE=Path(__file__).resolve().parent

def run_tests():
    spec=importlib.util.spec_from_file_location('review',HERE/'validate-independent-review.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
    assert m.validate_records(m.load_records())['status']=='passed'
    cases=[]
    def add(name,doc,path,value):cases.append((name,doc,path,value))
    for name,path,value in [
        ('wrong_id',('scope_aw_ids',0),'lakes_base:0000'),('false_increment',('current_batch_increment',),4),('inflated_total',('cumulative_distinct_targets',),112),('wrong_baseline',('baseline_commit',),'0'*40),('lost_pending',('preserved_pending_access_ids',),[]),('lost_prior_holds',('preserved_scope_hold_ids',),[]),('lost_new_holds',('new_scope_hold_ids',),[]),('hold_as_access_failure',('new_pending_access_ids',),['lakes_base:1159112237']),('automatic_application',('automatic_application',),True),('prior_reaudit',('prior_target_source_or_geometry_reaudit_performed',),True),('decoder_replay',('private_original_packed_decoder_independently_replayed',),True),('public_replays_omitted_evidence',('historical_review','historical_results_recomputed_by_public_validator'),True),('false_hold_total',('current_batch_scope_hold_targets',),3),('false_followup_total',('current_batch_follow_up_required_targets',),3),('uncompleted_comparison',('independent_source_comparison_completed',),False)]:add(name,'review',path,value)
    for i in range(3):
        for name,path,value in [
            ('wrong_fid',('geometry_fids',),[0]),('wrong_logical_fid',('baseline_logical_fid',),0),('wrong_positions',('position_count_including_closure',),0),('omitted_rings',('all_selected_parts_and_rings_considered',),False),('invented_part',('polygon_part_count',),2),('wrong_fact_link',('source_observation_id',),'lakes_base:0000'),('lost_location',('geographic_disambiguation',),''),('lost_followup_scope',('follow_up_scope',),''),('wrong_category',('research_category',),'invented'),('wrong_status',('review_status',),'invented'),('wrong_name_role',('candidate_name_role',),'invented'),('scalar_name',('whole_feature_scalar_name',),'Invented Lake'),('korean_name',('name_ko',),'이름'),('exact_shore',('exact_shoreline_verified',),True),('not_registered',('registered_overlay_performed',),False),('lost_extent_limit',('naming_scope_details','material_extent_limit'),''),('entire_lake_claim',('naming_scope_details','entire_detailed_named_lake_representation_verified'),True),('exact_component_assignment',('naming_scope_details','component_associations_are_exact_geometric_assignments'),True),('product_application',('product_application',),True),('wrong_source_name',('directly_supported_name_forms',),['Invented Lake']),('wrong_candidate',('candidate_name',),'Invented Lake'),('full_coordinates',('coordinates',),[[1,2],[3,4]])]:add(name+'_'+str(i),'review',('findings',i)+path,value)
        add('wrong_geometry_type_'+str(i),'geometry',('selected_features',i,'source_geometry','type'),'MultiPolygon')
        add('lost_ring_'+str(i),'geometry',('selected_features',i,'baseline_rendered_geometry','coordinate_counts_by_part_and_ring'),[[1]])
        add('missing_observation_'+str(i),'source',('complete_feature_observations',i,'independent_observation'),'')
    for name,path,value in [
        ('drop_misty',('findings',0,'candidate_names'),['Lac Brochet']),('kingsley_component',('findings',0,'candidate_names'),['Misty Lake','Lac Brochet','Kingsley Lake']),('exhaustive_compound_names',('findings',0,'naming_scope_details','supported_component_names_exhaustive'),True),('lost_compound',('findings',0,'naming_scope_details','multiple_named_lakes_in_one_polygon'),False),('lost_corridor_scope',('findings',0,'naming_scope_details','unresolved_named_extents'),[]),('lost_kasmere_identity',('findings',1,'naming_scope_details','whole_polygon_single_name_supported'),False),('kasmere_as_hold',('findings',1,'follow_up_required'),True),('tice_alias',('findings',1,'candidate_names'),['Kasmere Lake','Tice Lake']),('forced_bannock_candidate',('findings',2,'candidate_name'),'Bannock Lake'),('bannock_component',('findings',2,'candidate_names'),['Bannock Lake']),('forced_wollaston',('findings',2,'directly_supported_name_forms'),['Wollaston Lake']),('forced_watson',('findings',2,'candidate_names'),['Watson Lake']),('unnamed_lobe_as_generalized',('findings',2,'naming_scope_details','whole_polygon_single_name_supported'),True),('lost_unnamed_lobe_scope',('findings',2,'naming_scope_details','unresolved_named_extents'),[]),('false_selected_name_confidence',('findings',2,'name_confidence','local_named_water_association'),'high'),('bannock_as_naming_source',('findings',2,'source_keys'),['wsa_completed_watershed_plans_2014']),('lost_saskatchewan_context',('findings',2,'context_source_keys'),[])]:add(name,'review',path,value)
    for name,path,value in [
        ('wrong_source_count',('distinct_reviewed_publications',),2),('false_dataset_independence',('underlying_hydrographic_dataset_independence_verified',),True),('inflated_naming_publications',('distinct_cartographic_identity_publications',),3),('inflated_source_groups',('independent_source_groups',),4),('new_acquisition',('new_original_source_acquisitions_this_batch',),1),('external_request',('new_external_requests',),1),('review_external_request',('new_external_requests_by_independent_reviewer',),1),('backend_total',('backend_http_subrequest_count',),1),('wrong_request_count_unit',('external_request_count_unit',),'http_requests'),('uncompleted_research_comparison',('independent_review_and_source_research_agree',),False),('private_fingerprint',('original_body_sha256',),'0'*64),('private_path',('local_path',),'/'.join(['','workspace','private'])),('invented_geology_day',('observations',0,'publication_date'),'2024-10-21'),('wrong_geology_precision',('observations',0,'publication_date_precision'),'day'),('invented_wsa_publication_date',('observations',1,'publication_date'),'2014-11-25'),('wrong_wsa_production',('observations',1,'printed_production_date'),'2025-05-01'),('wsa_retain_as_acquire',('observations',1,'original_acquisition_batch'),'r17'),('electoral_retain_as_acquire',('observations',2,'original_acquisition_batch'),'r17'),('normalized_ambiguous_date',('observations',2,'printed_creation_date_normalized'),'2023-02-10'),('wrong_electoral_date_order',('observations',2,'printed_creation_date_order'),'month/day/year'),('electoral_publication_claim',('observations',2,'publication_date'),'2023-02-10'),('invented_electoral_scale',('observations',2,'printed_scale'),'1:1,000,000'),('lost_electoral_time_basis',('observations',2,'original_acquisition_timestamp_basis'),''),('request_time_as_acquired',('observations',2,'original_acquired_at_utc'),'2026-10-09T17:19:23.772516+00:00')]:add(name,'source',path,value)
    for i in range(3):
        for name,path,value in [('wrong_url',('url',),'https://example.invalid'),('failed_http',('acquisition_http_status',),403),('false_reuse',('reused_original',),False),('new_retrieval',('retrieved_this_batch',),True),('registry_claim',('is_formal_naming_registry',),True),('not_viewed',('original_map_pixels_viewed',),False),('wrong_labels',('directly_read_water_labels',),['Invented Lake'])]:add(name+'_'+str(i),'source',('observations',i)+path,value)
    for name,path,value in [('false_duplicate',('intersection_aw_ids',),['lakes_base:1159112221']),('wrong_remaining',('current_batch_delta','remaining_fresh_reconstruction_queue_after'),3955),('wrong_lake_remaining',('current_batch_delta','remaining_queue_types_after','lake'),543),('wrong_prior_pin',('previous_index_immutable_url',),'https://example.invalid')]:add(name,'continuity',path,value)
    rejected=[]
    for name,doc,path,value in cases:
        data=copy.deepcopy(m.load_records());target=data[doc]
        for k in path[:-1]:target=target[k]
        target[path[-1]]=value
        try:m.validate_records(data)
        except(AssertionError,KeyError,TypeError,ValueError):rejected.append(name)
        else:raise AssertionError('Corrupt record accepted: '+name)
    try:m.verify_bytes(b'changed',{'bytes':1,'sha256':'0'*64})
    except AssertionError:rejected.append('included_byte_integrity')
    else:raise AssertionError('Changed bytes accepted')
    return {'status':'passed','semantic_and_integrity_mutations_rejected':rejected,'network_requests':0,'original_map_or_full_polygon_or_decoder_judgments_reproduced':False}
if __name__=='__main__':print(json.dumps(run_tests(),indent=2))
