import { initializeTestTerritorialState } from '../helpers/timeline-project.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import '../../assets/js/vendor/polygon-clipping.min.js';
import { createTerritorialEntityStore } from '../../assets/js/modules/territorial-entity-store.js';
import { createTerritorialEntityRepository } from '../../assets/js/modules/territorial-entity-repository.js';
import { createTerritorialScopeResolver } from '../../assets/js/modules/territorial-scope.js';
import { createTerritorialFeature } from '../../assets/js/modules/territorial-units.js';
import { hasCanonicalPolygonWinding, area } from '../../assets/js/modules/map-edit-geometry.js';
const square = (x0, x1) => ({ type: 'Polygon', coordinates: [[[x0,0],[x0,2],[x1,2],[x1,0],[x0,0]]] });

test('every general hierarchy level has an immutable canonical display extent; independent regions retain their own shape', () => {
  const make = (id, parentId, x0, x1, entityKind = 'general') => createTerritorialFeature({ id, entityKind, parentId, geometry: square(x0,x1) });
  const state = { territorialEntities: [make('A','',0,2),make('B','A',1,3),make('C','B',2,4),make('D','',5,7),make('R','',0,10,'regional')] };
  initializeTestTerritorialState(state);
const store = createTerritorialEntityStore({ getState: () => state });
  const repo = createTerritorialEntityRepository({ entityStore: store });
  const scope = createTerritorialScopeResolver({ entityRepository: repo, getState: () => state, clipper: () => globalThis.polygonClipping });
  const before = structuredClone(state.territorialEntities);
  const first = scope.scope('A');
  assert.strictEqual(scope.scope('A'), first);
  assert.deepEqual(first.members.map(entity=>entity.id), ['B','C']);
  assert.equal(first.extent.id, 'A');
  assert.equal(area(first.extent.geometry), 8);
  assert.equal(area(scope.scope('B').extent.geometry), 6);
  assert.equal(area(scope.scope('B').extra.geometry), 2);
  assert.equal(hasCanonicalPolygonWinding(first.extent.geometry), true);
  const region = scope.scope('R');
  assert.strictEqual(region.extent, repo.get('R'));
  assert.deepEqual(region.members, []);
  assert.deepEqual(state.territorialEntities, before);
  store.applyChanges({ features: [{ ...repo.get('B'), properties: { ...repo.get('B').properties, parentId: 'D' } }] });
  assert.equal(area(scope.scope('A').extent.geometry), 4);
  assert.notStrictEqual(scope.scope('A'), first);
  assert.equal(repo.root('C').id, 'D');
  assert.equal(area(scope.scope('D').extent.geometry), 10);
  assert.deepEqual(scope.scope('R').extent.geometry, region.extent.geometry);
});
